package com.binayshaw7777.kotstep.utils


enum class StepperOptions {
    HORIZONTAL_SEQUENCED_STEPPER,
    VERTICAL_SEQUENCED_STEPPER,
    HORIZONTAL_ICON_STEPPER,
    VERTICAL_ICON_STEPPER,
    HORIZONTAL_STEPPER,
    HORIZONTAL_SOLID_STEPPER,
    HORIZONTAL_DASHED_STEPPER,
    VERTICAL_STEPPER
}