package com.binayshaw7777.kotstep.utils


enum class StepperTypes {
    HORIZONTAL_SEQUENCED_STEPPER,
    VERTICAL_SEQUENCED_STEPPER,
    HORIZONTAL_ICON_STEPPER,
    VERTICAL_ICON_STEPPER,
    HORIZONTAL_STEPPER,
    VERTICAL_STEPPER
}